<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <PackageTags>open-systems-pharmacology, ospsuite-components</PackageTags>
    <Authors>Open-Systems-Pharmacology</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <NoWarn>1591</NoWarn>
    <Version Condition="'$(Version)' == ''">13.0.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\SolutionInfo.cs" Link="Properties\SolutionInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OSPSuite.Assets.Images" Version="13.0.134" />
    <PackageReference Include="DevExpress.Win" Version="25.2.7" />
    <PackageReference Include="DevExpress.Win.BonusSkins" Version="25.2.7" />
    <PackageReference Include="DevExpress.Win.Charts" Version="25.2.7" />
    <PackageReference Include="DevExpress.Win.RichEdit" Version="25.2.7" />
    <PackageReference Include="DevExpress.Win.Design" Version="25.2.7" Condition="'$(ExcludeDesigner)' != 'true'" />
    <PackageReference Include="OSPSuite.FuncParser" Version="5.0.0.3" />
    <PackageReference Include="OSPSuite.Infrastructure" Version="13.0.134" />
    <PackageReference Include="OSPSuite.Infrastructure.Castle" Version="13.0.134" />
    <PackageReference Include="OSPSuite.Presentation" Version="13.0.134" />
    <PackageReference Include="OSPSuite.SimModel" Version="5.0.0.76" />
    <PackageReference Include="OSPSuite.Utility" Version="5.0.0.10" />
    <PackageReference Include="OSPSuite.Core" Version="13.0.134" />
    <PackageReference Include="OSPSuite.Assets" Version="13.0.134" />
    <PackageReference Include="QuestPDF" Version="2024.3.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>


</Project>
