name: Build Nightly 13.0
run-name: Version 13.0.${{ github.run_number }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # Weekly build to verify that code signing still works

permissions:
  contents: read
  packages: read

jobs:
  build-nightly:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Restore dependencies
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"
          nuget restore

      - name: define env variables
        run: |
          echo "APP_VERSION=13.0.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        env:
          DevExpress_License: ${{ secrets.DEV_EXPRESS_KEY }}
        run: |
          dotnet build InstallationValidator.sln /p:Version=${{env.APP_VERSION}} -p:ExcludeDesigner=true

      - name: Test
        run: dotnet test InstallationValidator.sln --no-build -v normal  --logger:"html;LogFileName=${{ github.workspace }}/testLog_Windows.html"

      - name: Sign InstallationValidator.exe with CodeSignTool
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/codesigner-SSL@main
        env:
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
        with:
          file_path: ./src/InstallationValidator/bin/Debug/net10.0-windows/InstallationValidator.exe

      - name: Sign SimulationOutputComparer.exe with CodeSignTool
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/codesigner-SSL@main
        env:
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
        with:
          file_path: ./src/SimulationOutputComparer/bin/Debug/net10.0-windows/SimulationOutputComparer.exe

      - name: Create Setup
        run: |
          rake "create_setup[${{env.APP_VERSION}}, Debug]"

      - name: Sign InstallationValidator setup with CodeSignTool
        uses: Open-Systems-Pharmacology/Workflows/.github/actions/codesigner-SSL@main
        env:
          ES_USERNAME: ${{ secrets.ES_USERNAME }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
          ES_CREDENTIAL_ID: ${{ secrets.ES_CREDENTIAL_ID }}
          ES_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
        with:
          file_path: ./setup/deploy/InstallationValidator.${{ env.APP_VERSION }}.msi

      - name: Push test log as artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: testLog_Windows
          path: ./testLog*.html

      - name: Push nightly installer as artifact
        uses: actions/upload-artifact@v7
        with:
          name: Installation Validator Installer ${{env.APP_VERSION}}
          path: setup\deploy\*.msi
