name: Build and Test

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

permissions:
  contents: read
  packages: read

jobs:
  build:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/test-csharp.yml@add_filter_for_tests
    secrets: inherit
    with:
      temp-version: "12.3.9999"
      test-arguments: "--filter TestCategory!=Reporting"